# Generated by Django 5.2.17 on 2026-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, default='csv', max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='brand_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Public https:// logo. Gmail cannot load images from localhost.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=80),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='logo',
            field=models.ImageField(blank=True, upload_to='templates/logos/'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Public https logo URL so Gmail can load the image.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_body',
            field=models.TextField(help_text='Use {{placeholders}} such as {{name}}, {{heading}}, {{body}}, {{logo_block}}'),
        ),
    ]
