# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_lead_pipeline_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="editor_mode",
            field=models.CharField(
                choices=[
                    ("template", "Template"),
                    ("simple", "Simple editor"),
                    ("html", "HTML custom code"),
                    ("dragdrop", "Drag and drop"),
                ],
                default="template",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="html_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="blocks_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="heading",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
