# Generated by Django 5.2.17 on 2026-09-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_sendlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='html_content',
            field=models.TextField(blank=True, help_text='Full or fragment HTML from Simple / HTML / Drag-drop editors.'),
        ),
    ]
