# Generated by Django 5.2.17 on 2026-09-07 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_repair_campaign_blocks_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('smtp_host', models.CharField(default='smtp.hostinger.com', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password_encrypted', models.TextField(blank=True)),
                ('credential_env_key', models.CharField(blank=True, help_text='Optional env var name holding the SMTP password instead of the encrypted field.', max_length=120)),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('daily_limit', models.PositiveIntegerField(default=300)),
                ('hourly_limit', models.PositiveIntegerField(default=50)),
                ('min_interval_seconds', models.PositiveIntegerField(default=12, help_text='Minimum pause after this mailbox sends, so Hostinger burst limits are respected.')),
                ('sent_today', models.PositiveIntegerField(default=0)),
                ('sent_this_hour', models.PositiveIntegerField(default=0)),
                ('day_key', models.DateField(blank=True, null=True)),
                ('hour_key', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_smtp_error', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('bounce', 'Hard bounce'), ('unsubscribe', 'Unsubscribe'), ('complaint', 'Complaint'), ('manual', 'Manually blocked')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Suppression entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('deferred', 'Deferred'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('bounced', 'Bounced')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('reserved', 'Reserved'), ('sent', 'Sent'), ('failed', 'Failed'), ('deferred', 'Deferred'), ('bounced', 'Hard bounced'), ('suppressed', 'Suppressed')], default='queued', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=400)),
                ('smtp_code', models.CharField(blank=True, max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_jobs', to='campaigns.campaign')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_job', to='campaigns.recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_jobs', to='campaigns.senderaccount')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('temporary', 'Temporary 4xx / retry'), ('permanent', 'Permanent 5xx'), ('connection', 'Connection / timeout'), ('suppressed', 'Suppressed'), ('skipped', 'Skipped')], max_length=20)),
                ('smtp_code', models.CharField(blank=True, max_length=20)),
                ('smtp_response', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='campaigns.emailjob')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='campaigns.senderaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unsub_row', to='campaigns.recipient')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='campaigns_e_status_e89699_idx'),
        ),
        migrations.AddIndex(
            model_name='emailjob',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_e_campaig_4ebcad_idx'),
        ),
    ]
